# Generated by Django 5.2.15 on 2026-06-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_project_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TD', 'To Do'), ('IP', 'In Progress'), ('RV', 'Review'), ('CP', 'Completed')], default='TD', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
